### ISSUE TITLE
How to do leaderboard for benchmarks?

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#433]
```yaml
# task definition
task:
  name: "Some new dataset to process"
  input_data: some_file.zip
  columns:
    - title: Duration
      key: duration
      sorting: desc
    - title: Accuracy
      key: accuracy
      sorting: desc
    - title: RMSC Accuracy
      key: rmsc_accuracy
      sorting: desc
    

# The above task, if first in the competition (assuming starting at count 1), would
# produce the following leaderboard keys
#     1_duration
#     1_accuracy
#     1_rmsc_accuracy


# task definition
task:
  name: "Some new dataset to process"
  input_data: some_other_file.zip
  columns:
    - title: Duration
      key: duration
      sorting: desc
    - title: Accuracy
      key: accuracy
      sorting: desc
    - title: RMSC Accuracy
      key: rmsc_accuracy
      sorting: desc
    
# The above task, if second in the competition (assuming starting at count 1), would
# produce the following leaderboard keys
#     2_duration
#     2_accuracy
#     2_rmsc_accuracy

```
